### ISSUE TITLE
3.10.6/5 does not compiled my GM on macOS 

### ISSUE THREAD

**Issue by F96fedebike** [pawn-lang/compiler#297] opened 2018-04-16 18:07 UTC
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [ ] Bug Report
* [ ] Feature Request
* [x] Question

**What happened**: When I'll try to compile my Gamemode with the last compiler update 3.10.5 or 3.10.6 I'll receive this error: 

dyld: Library not loaded: @rpath/libpawnc.dylib
 Referenced from: /Users/federico/Desktop/Pawno/./pawncc
Reason: image not found
[Finished in 0.0s with exit code -6]

With the old release 3.10.4 o more old don't have any problems. 

For invoke the compiler I use this:

`"cmd": ["./pawncc", "$file", "-iinclude", "-o$file_path/$file_base_name","-Z+","-;+","-(+", "-d3"],
	"file_regex": "^([^\\.]+\\.pwn)\\((\\d+)\\)() : (.*)$",
	"working_dir": "/Users/federico/Desktop/Pawno"`

**Environment**:

* Operating System: MacOS High Sierra
* Compiler version: 3.10.6
* How are you invoking the compiler?  Sublime

**Comment by Southclaws** [comment] 2018-04-16 20:54
You should set the environment variable `DYLD_LIBRARY_PATH=/path/to/dir` where `dir` contains the pawn `.dylib` file.

I'm not sure if sublime supports the prefix notation for env vars, like: `DYLD_LIBRARY_PATH=/path/to/dir ./pawncc` you may need to do this externally or via a script.

**Comment by F96fedebike** [comment] 2018-04-16 23:08
@Southclaws I'll try with this: https://packagecontrol.io/packages/Environment%20Settings 
But i have the same error but I don't have mean why with older release it's ok.

**Comment by Southclaws** [comment] 2018-04-17 06:49
Strange, I can't reproduce this on my mac with sampctl with compiler 3.10.5 or 3.10.6, I am defining two variables:

https://github.com/Southclaws/sampctl/blob/6303cf263bc7e52a0ac4489efaa3b65cbe24269f/compiler/compiler.go#L163-L164

**Comment by F96fedebike** [comment] 2018-04-17 14:47
@Southclaws I've tried with sampctl with VS Code and worked.
Now I've tried with Sublime and I have see it's more slower than a few seconds to compiling.

Is not possible to enable the classic Pawn console debug with memory use etc?

**Comment by Southclaws** [comment] 2018-04-17 18:53
> Is not possible to enable the classic Pawn console debug with memory use etc?

With pawncc: `-v` with sampctl: `--verbose`

**Comment by F96fedebike** [comment] 2018-04-17 20:39
@Southclaws I've tried but show me the same list of --Help...

**Comment by Southclaws** [comment] 2018-04-18 09:10
If the original issue is resolved, please close it and if you're having problems with sampctl then [open an issue here](https://github.com/Southclaws/sampctl/issues) or contact me on the [SA:MP discord server](http://discord.me/samp).

**Closed** 2018-04-18 10:47 UTC
