### ISSUE TITLE
Another assertation failure

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#399] opened 2019-01-06 14:01 UTC
### Minimal complete verifiable example (MCVE):

```pawn
public Func() <anything>
{
}

main()
{
	__file();
}
```

Unlike #398 which I found at almost the same time, this one seems to be triggered by `__file` not `__line`, and gives this failure:

`glb_declared==0`

### Workspace Information:

* Compiler version: 3.10.9
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Daniel-Cortez** [comment] 2019-06-28 12:14
Most probably a duplicate of #156.

**Closed** 2019-09-21 21:53 UTC
