### ISSUE TITLE
Remove the dependency on sNAMEMAX (increasing the maximum symbol name length)

### ISSUE THREAD

**Issue by IllidanS4** [pawn-lang/compiler#381] opened 2018-10-16 15:35 UTC
### Issue description:
The AMX headers define `sNAMEMAX` to be 31 characters, and the compiler uses this constant in every table containing symbol information. Removing this arbitrary limitation completely would be primarily useful for macros which need to generate symbol names based on existing symbols, or for targetting AMX runtimes with [LFN](https://forum.sa-mp.com/showthread.php?t=659789) support when in need of longer names in the API or unusual features (like [name mangling](https://github.com/IllidanS4/pawn-conventions/blob/master/name-mangling.md)).

Since this would require rewriting all definitions to use dynamically allocated names anyway (increasing the limit to 63 or 255 etc. doesn't solve the issue and slows down all allocations as the result), I see no point in having to enable this feature via a compiler option or pragma for non-public names. Code compiled under previous versions of the compiler would either be unaffected, or report a warning, whereas code in the new version would either behave the same, or work as expected, respectively.

The matter is different for public symbols (functions, variables, tags, libraries). Since the runtime usually doesn't allow AMX programs with longer symbol names, it makes sense for the compiler to disallow public symbol names longer than 31 characters by default. Then there should be an option that increases this limit to 65535 (since the maximum length is stored in the AMX header as an uint16).

### Minimal complete verifiable example (MCVE):
```pawn
native VeryLongNativeFunctionNameExceeding31Characters();

public VeryLongPublicFunctionNameExceeding31Characters()
{
    
}

public VeryLongPublicVariableNameExceeding31Characters;

new VeryLongVariableNameExceeding31Characters;

VeryLongNormalFunctionNameExceeding31Characters()
{
    
}
```

**Comment by Y-Less** [comment] 2018-10-16 15:42
https://github.com/pawn-lang/compiler/issues/102

**Comment by Southclaws** [comment] 2018-10-16 15:42
*almost* duplicate of #39

**Closed by Y-Less** 2018-10-16 15:42 UTC

**Comment by Southclaws** [comment] 2018-10-17 14:52
I'm inviting discussion around this topic to continue despite the issue being closed.

Yes, publics can't be touched however, in my understanding, symbols such as preprocessor definitions and non-public functions/variables may be candidates for adjustment. I'd advocate for any changes to be put behind feature-flags still.

**Comment by IllidanS4** [comment] 2018-10-17 15:10
`#define VeryLongFunctionName VLFN` can solve the need for long symbol names in most cases, but several libraries decorate non-public symbol names in some way, causing warnings potentially even if shorter names (i.e. "good" names) are used. For the users of such a library, having the shortest affix is the best, but once multiple such libraries are used, having the _longest_ affix is the most desirable (to reduce potential conflicts).

**Comment by YashasSamaga** [comment] 2018-10-17 15:28
Few points to consider:
- breaks many libraries
- breaks plugins

**Comment by IllidanS4** [comment] 2018-10-18 09:07
Plugins should use `amx_NameLength` when working with public names, so they're out of the question. Thinking about libraries, they should be configurable to allow an increased limit, but exporting the maximum length as some `NAMEMAX`-like definition would be nice as well.

However, since the compiler does not know the maximum length before parsing the whole script, the proposed option should only increase the limit, not remove it completely. So, for example, the option `-nl 63` would export `__NAMEMAX` as 63. `-nl -1` could be allowed as well (in which case `__NAMEMAX` would not be exported), but it is not necessary, since one could always increase the limit based on the script requirements. The majority of the changes necessary to implement this is still the same, so the option is just a cosmetic change.

Names longer than `__NAMEMAX` shall be truncated and report a warning as usual. Public names longer than 31 characters shall do the same, unless `#pragma pubnamelen` (or similar, push/pop) is used.
